### ISSUE TITLE
Response validator: "Stimulus" of multipart questions not taken into account

### ISSUE THREAD

**Issue by reedstrm** [openstax/response-validator#19]
Multipart exercises, which often contain a common "stimulus" part, with multiple questions relating to a single block of text, are currently treated as separate questions.  The vocabulary in the stimulus text is ignored, with only the individual questions and answer/option texts being converted into vocabulary

**Comment by reedstrm** [comment]
@aew2  - opinion on what to do w/ the stimulus text in the backend. Do we want to keep it with every question from the exercise, or track it separately, like options vs. question words?

**Comment by reedstrm** [comment]
Discussed in person w/ @aew2  - decided to add the exercise-level stimulus to each question's text for purposes of vocabulary.

**Comment by LogisticAggression010** [comment]
Spoke with @reedstrm about this today.  We can reimport the books to include the stimulus html and then just aggregate all words together across a multipart problem to "cover" everything.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
