### ISSUE TITLE
Condition that is ignored

### ISSUE THREAD

**Issue by Dantemss** [openstax/response-validator#22]
`has_numeric` in the line below is basically ignored because a value of `"auto"` is truthy, so it will just return `"auto"` in that case.

https://github.com/openstax/response-validator/pull/21/files/0f5f154859802dc979d276897ced152d1e7c69ea#diff-64c2c6df0e5c393e9d1139bc9eb87fc0R215

**Comment by reedstrm** [comment]
lazy math may be too lazy.

**Comment by carlycurran** [comment]
@aew2, Ross said you are the man for this job!

**Comment by LogisticAggression010** [comment]
@carlycurran @reedstrm @Dantemss 

I agree with Dante that this isn't right.  We should be passing True if tag_numeric is True, or if tag_numeric is "auto" and has_numeric is True.

tag_numeric = (tag_numeric==True) or (tag_numeric=='auto' and has_numeric)

However, I don't think this is a huge deal at all given how little the numeric parser is doing at this point.  Where this line would get us into trouble is if students were spamming numbers to get through the validity check, which they currently aren't doing.  Lazy math mode (starting line 261) is working fine and is making sure that math-ey questions are very forgiving on responses, which was the bigger concern that we had.

So if this is an easy change to make at this point I am all for it but if it isn't it definitely isn't a showstopper and can wait a bit.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
